version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432" # Прокидання порту
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hr_db
    volumes:
      - db_data:/var/lib/postgresql/data # Збереження даних у файловій системі

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  db_data:
